services:
  
  db:
      image: postgres:13-alpine
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: chess_app_db
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      mem_limit: 128m
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #       - "8000:8000"
  #   env_file:
  #     - .env
  #   mem_limit: 256m

volumes:
  db_data: